name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: external workflow
    uses: tehw0lf/workflows/.github/workflows/build-test-publish.yml@main
    permissions:
      actions: write
      contents: write
      packages: write
    with:
      event_name: ${{ github.event_name }}
      docker_meta: '[{"name":"fwdark","file":"Dockerfile"}]'
      platforms: "linux/arm64"
